global using System.Diagnostics;
global using System.Xml;
global using BlackDesert.Trade.Domain.Common;
global using BlackDesert.Trade.Domain.Models;
global using System.Configuration;
global using BlackDesert.Trade.Domain.Common;
global using BlackDesert.Trade.Domain.Models;
global using System.Data.Entity.Core.Objects;
global using Newtonsoft.Json;
global using ConfigurationManager = System.Configuration.ConfigurationManager;
global using Serilog;
global using Microsoft.EntityFrameworkCore;