//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackDesert.Trade.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackDesert.Trade.Domain.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 만 [STR:AGE]세 미만인 사용자는 게임을 이용할 수 없습니다..
        /// </summary>
        internal static string NEW_WEB_MSG_DEFAULT_AUTHENTICATEACCOUNT_FAIL_AGE {
            get {
                return ResourceManager.GetString("NEW_WEB_MSG_DEFAULT_AUTHENTICATEACCOUNT_FAIL_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전체 목록.
        /// </summary>
        internal static string TRADE_MARKET_ALL_LIST {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ALL_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [STR:SUBTYPE] [STR:ITEMNAME] [STR:ITEMCOUNT]개 구매 완료했습니다. [STR:SILVER]은화.
        /// </summary>
        internal static string TRADE_MARKET_ALRAM_BUY {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ALRAM_BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [STR:SUBTYPE] [STR:ITEMNAME] [STR:ITEMCOUNT]개 구매 예약 완료했습니다. [STR:SILVER]은화.
        /// </summary>
        internal static string TRADE_MARKET_ALRAM_BUY_BIDDING {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ALRAM_BUY_BIDDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [STR:SUBTYPE] [STR:ITEMNAME] [STR:ITEMCOUNT]개 구매 예약에서 회수했습니다. [STR:SILVER]은화.
        /// </summary>
        internal static string TRADE_MARKET_ALRAM_BUY_BIDDING_CANCEL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ALRAM_BUY_BIDDING_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 예약한 [STR:SUBTYPE] [STR:ITEMNAME] [STR:ITEMCOUNT]개 정산했습니다. [STR:SILVER]은화.
        /// </summary>
        internal static string TRADE_MARKET_ALRAM_BUY_BIDDING_CANCEL_CALCULATE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ALRAM_BUY_BIDDING_CANCEL_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        internal static string TRADE_MARKET_ALRAM_CLOSE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ALRAM_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [STR:SUBTYPE] [STR:ITEMNAME] [STR:ITEMCOUNT]개 판매 완료했습니다. [STR:SILVER]은화.
        /// </summary>
        internal static string TRADE_MARKET_ALRAM_SELL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ALRAM_SELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [STR:SUBTYPE] [STR:ITEMNAME] [STR:ITEMCOUNT]개 판매 예약 완료했습니다. [STR:SILVER]은화.
        /// </summary>
        internal static string TRADE_MARKET_ALRAM_SELL_BIDDING {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ALRAM_SELL_BIDDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [STR:SUBTYPE] [STR:ITEMNAME] [STR:ITEMCOUNT]개 판매 예약에서 회수했습니다. [STR:SILVER]은화.
        /// </summary>
        internal static string TRADE_MARKET_ALRAM_SELL_BIDDING_CANCEL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ALRAM_SELL_BIDDING_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 예약한 [STR:SUBTYPE] [STR:ITEMNAME] [STR:ITEMCOUNT]개 정산했습니다. [STR:SILVER]은화.
        /// </summary>
        internal static string TRADE_MARKET_ALRAM_SELL_BIDDING_CANCEL_CALCULATE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ALRAM_SELL_BIDDING_CANCEL_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 알림내역.
        /// </summary>
        internal static string TRADE_MARKET_ALRAM_TITLE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ALRAM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 대기.
        /// </summary>
        internal static string TRADE_MARKET_BIDDING_BUY_WAIT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BIDDING_BUY_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [STR:ITEMCOUNT] 건.
        /// </summary>
        internal static string TRADE_MARKET_BIDDING_EA {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BIDDING_EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 대기.
        /// </summary>
        internal static string TRADE_MARKET_BIDDING_SELL_WAIT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BIDDING_SELL_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이 사이트는 모바일 브라우저에 최적화 되어 있습니다. 통합거래소를 원활하게 이용하기 위해 모바일 브라우저를 이용하시길 권장합니다..
        /// </summary>
        internal static string TRADE_MARKET_BROWSER_MSG {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BROWSER_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 완료.
        /// </summary>
        internal static string TRADE_MARKET_BUY_BIDDING_BOUGHT_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_BIDDING_BOUGHT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정산.
        /// </summary>
        internal static string TRADE_MARKET_BUY_BIDDING_CALCULATE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_BIDDING_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매예약을 취소하시겠습니까?.
        /// </summary>
        internal static string TRADE_MARKET_BUY_BIDDING_CANCEL_CONFIRM {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_BIDDING_CANCEL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 예약 개수.
        /// </summary>
        internal static string TRADE_MARKET_BUY_BIDDING_RESERVE_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_BIDDING_RESERVE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 예약 완료하였습니다..
        /// </summary>
        internal static string TRADE_MARKET_BUY_BIDDING_SUCCESS {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_BIDDING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소.
        /// </summary>
        internal static string TRADE_MARKET_BUY_BIDDING_WITHDRAW {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_BIDDING_WITHDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 취소.
        /// </summary>
        internal static string TRADE_MARKET_BUY_CANCEL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 확인.
        /// </summary>
        internal static string TRADE_MARKET_BUY_CONFIRM {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 돌파 등급.
        /// </summary>
        internal static string TRADE_MARKET_BUY_ENCHANT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_ENCHANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 실패.
        /// </summary>
        internal static string TRADE_MARKET_BUY_FAIL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 확인.
        /// </summary>
        internal static string TRADE_MARKET_BUY_OK {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 가격.
        /// </summary>
        internal static string TRADE_MARKET_BUY_PRICE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 변경.
        /// </summary>
        internal static string TRADE_MARKET_BUY_PRICE_CHANGE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_PRICE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 수량.
        /// </summary>
        internal static string TRADE_MARKET_BUY_QUANTITY {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매를 완료하였습니다..
        /// </summary>
        internal static string TRADE_MARKET_BUY_SUCCESS {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 총 구매 금액.
        /// </summary>
        internal static string TRADE_MARKET_BUY_TOTAL_PRICE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_BUY_TOTAL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 물품 수령.
        /// </summary>
        internal static string TRADE_MARKET_CALC_BUY {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소.
        /// </summary>
        internal static string TRADE_MARKET_CALC_BUY_CANCEL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_BUY_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        internal static string TRADE_MARKET_CALC_BUY_CLOSE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_BUY_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 완료.
        /// </summary>
        internal static string TRADE_MARKET_CALC_BUY_COMPLETE_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_BUY_COMPLETE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 물품 수령.
        /// </summary>
        internal static string TRADE_MARKET_CALC_BUY_CONFIRM {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_BUY_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 개당 단가.
        /// </summary>
        internal static string TRADE_MARKET_CALC_BUY_PRICE_PER_ONE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_BUY_PRICE_PER_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 예약 개수.
        /// </summary>
        internal static string TRADE_MARKET_CALC_BUY_RESERVE_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_BUY_RESERVE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 물품거래 수수료는 30% 입니다..
        /// </summary>
        internal static string TRADE_MARKET_CALC_BUY_TEX_INFO {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_BUY_TEX_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 총 구입 금액.
        /// </summary>
        internal static string TRADE_MARKET_CALC_BUY_TOTAL_PRICE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_BUY_TOTAL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 정산.
        /// </summary>
        internal static string TRADE_MARKET_CALC_SELL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_SELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소.
        /// </summary>
        internal static string TRADE_MARKET_CALC_SELL_CANCEL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_SELL_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        internal static string TRADE_MARKET_CALC_SELL_CLOSE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_SELL_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 개수.
        /// </summary>
        internal static string TRADE_MARKET_CALC_SELL_COMPLETE_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_SELL_COMPLETE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정산.
        /// </summary>
        internal static string TRADE_MARKET_CALC_SELL_CONFIRM {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_SELL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 금액.
        /// </summary>
        internal static string TRADE_MARKET_CALC_SELL_PRICE_PER_ONE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_SELL_PRICE_PER_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 개수.
        /// </summary>
        internal static string TRADE_MARKET_CALC_SELL_RESERVE_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_SELL_RESERVE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 물품거래 수수료는 30% 입니다..
        /// </summary>
        internal static string TRADE_MARKET_CALC_SELL_TEX_INFO {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_SELL_TEX_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 총 판매 금액.
        /// </summary>
        internal static string TRADE_MARKET_CALC_SELL_TOTAL_PRICE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CALC_SELL_TOTAL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시세 가격.
        /// </summary>
        internal static string TRADE_MARKET_CONDITION {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 보기.
        /// </summary>
        internal static string TRADE_MARKET_CONDITION_SHOW {
            get {
                return ResourceManager.GetString("TRADE_MARKET_CONDITION_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [STR:ITEMCOUNT]개.
        /// </summary>
        internal static string TRADE_MARKET_EA {
            get {
                return ResourceManager.GetString("TRADE_MARKET_EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 사용된 백업코드 입니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_BACKUPCODE_ALREADY_USE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_BACKUPCODE_ALREADY_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 예약구매를 시도하는 중 문제가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_BIDDING_FAIL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_BIDDING_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 거래가 중지된 아이템 입니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_BLOCK_ITEM {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_BLOCK_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 거래가 중지된 유저 입니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_BLOCK_USER {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_BLOCK_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 정산에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_CALC_ITEM_FAIL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_CALC_ITEM_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합 거래소 이용이 불가능한 상태입니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_CLOSE_MARKET {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_CLOSE_MARKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 거래소 계좌 생성에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_CREATE_WALLET_FAIL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_CREATE_WALLET_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 처리 중 오류가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_EXCEPTION {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 아이템이 판매 예약에 등록되어 구매 예약에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_HAVE_SELL_BIDDING_FAIL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_HAVE_SELL_BIDDING_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 정보가 유효하지 않습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_INVALID_ITEM {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_INVALID_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 수량이 유효하지 않습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_INVALID_ITEM_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_INVALID_ITEM_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색어가 유효하지 않습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_INVALID_SEARCH_TEXT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_INVALID_SEARCH_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 구매에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_ITEM_BUY_FAIL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_ITEM_BUY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 판매에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_ITEM_SELL_FAIL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_ITEM_SELL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인증코드를 10회 이상 잘못 입력하여 24시간 동안 입력이 제한되었습니다.\n도움이 필요하시면 고객센터로 문의해 주세요..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_MAXFAIL_OTP {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_MAXFAIL_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 보유 금액이 부족합니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_NOT_ENOUGH_MONEY {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_NOT_ENOUGH_MONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 거래소 계좌가 존재하지 않습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_NOT_EXISTS_WALLET {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_NOT_EXISTS_WALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 정보가 존재하지 않습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_NOT_EXSITS_ITEM {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_NOT_EXSITS_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유저 정보가 존재하지 않습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_NOT_EXSITS_USER {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_NOT_EXSITS_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인증코드가 일치하지 않습니다. 다시 한 번 확인해 주세요..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_NOTMATCH_OTP {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_NOTMATCH_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 수용 가능한 최대 적재량을 초과했습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_OVER_WEIGHT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_OVER_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가격 정보가 올바르지 않습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_PRICE_WORNG {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_PRICE_WORNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 등록에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_REGIST_ITEM_FAIL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_REGIST_ITEM_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 예약판매에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_SELL_BIDDING_FAIL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_SELL_BIDDING_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인증 정보가 올바르지 않습니다. 다시 로그인 해주세요..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 해당 아이템을 거래하려면 OTP 서비스를 사용해야 합니다.\nOTP 서비스는 마이페이지 &gt; 보안센터에서 사용 설정할 수 있습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_UNUSE_OTP {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_UNUSE_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 회수에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_ERROR_MSG_WITHDRAW_ITEM_FAIL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ERROR_MSG_WITHDRAW_ITEM_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 즐겨찾기 목록.
        /// </summary>
        internal static string TRADE_MARKET_FAVORIT_LIST {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FAVORIT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 필터 검색.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 평균 가격.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH_AVG_PRICE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH_AVG_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 돌파 등급.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH_ENCHANT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH_ENCHANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 높은 순.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH_HIGH {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 초기화.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH_INITIALIZE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH_INITIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오래.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH_LATER {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH_LATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 낮은 순.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH_LOW {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최근.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH_RECENT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH_RECENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록일.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH_REGDATE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH_REGDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 개수.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH_REGIST_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH_REGIST_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 적은 순.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH_REGIST_LOW {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH_REGIST_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 많은 순.
        /// </summary>
        internal static string TRADE_MARKET_FILTER_SEARCH_REGIST_MANY {
            get {
                return ResourceManager.GetString("TRADE_MARKET_FILTER_SEARCH_REGIST_MANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 예약되어 예약에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoAlreadyReservationDay {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoAlreadyReservationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 거래가 중지된 아이템입니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoBlockItem {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoBlockItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 거래가 중지된 유저 입니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoBlockUser {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoBlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 보유 금액이 부족합니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoBusinessNotEnoughMoney {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoBusinessNotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 대기가 걸리는 물품의 경우 점검 20분 전에는 등록할 수 없습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoCantSellItemShutDown {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoCantSellItemShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합 거래소가 이용 불가능한 상태입니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoCloseWorldMarket {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoCloseWorldMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 처리 중 내부 오류가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoDbInternalError {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoDbInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 아이템이 구매 예약에 등록되어 있어 판매 예약에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoHaveBuyBiddingInfoWorldMarket {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoHaveBuyBiddingInfoWorldMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 아이템이 판매 예약에 등록되어 구매 예약에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoHaveSellBiddingInfoWorldMarket {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoHaveSellBiddingInfoWorldMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템이 존재하지 않습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoInventoryItemNotExist {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoInventoryItemNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 개수가 비정상 입니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoItemCountIsInvalid {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoItemCountIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 개수가 잘못됐습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoItemInvalidCount {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoItemInvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 정산에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoNoCalculateItemWorldMarket {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoNoCalculateItemWorldMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계좌가 존재하지 않습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoNotExistWallet {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoNotExistWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계정 인증에 실패하였습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoPublisherFailAuthetication {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoPublisherFailAuthetication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 등록에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoRegistItemFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoRegistItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 판매 하는 가격보다 높은 가격으로 구매 중인 다른 직군의 물품이 있습니다. 해당 가격과 같거나 높게 판매 해야 합니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoRowPriceGroupBuy {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoRowPriceGroupBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 회수에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoWithdrawItemFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoWithdrawItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소 예약구매를 시도하는 중 문제가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketBuybiddingFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketBuybiddingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합 거래소 구매를 시도하는 중 문제가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketBuyFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketBuyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 계좌 생성에 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketCreateWalletFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketCreateWalletFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합 거래소의 수용 가능한 최대 적재량을 초과했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketIsNotMaxWeight {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketIsNotMaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소 예약판매를 시도하는 중 문제가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketSellbiddingFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketSellbiddingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합 거래소 판매를 시도하는 중 문제가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketSellFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GAME_ERROR_eErrNoWorldMarketSellFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 공식 홈페이지 바로가기.
        /// </summary>
        internal static string TRADE_MARKET_GO_NOTICE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GO_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 안내.
        /// </summary>
        internal static string TRADE_MARKET_GUIDE_TITLE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_GUIDE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 급등락 물품.
        /// </summary>
        internal static string TRADE_MARKET_HOT_LIST {
            get {
                return ResourceManager.GetString("TRADE_MARKET_HOT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 멸겁하는.
        /// </summary>
        internal static string TRADE_MARKET_ITEM_DEAD_FIVE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ITEM_DEAD_FIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 울부짖는.
        /// </summary>
        internal static string TRADE_MARKET_ITEM_DEAD_FOUR {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ITEM_DEAD_FOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 갈망하는.
        /// </summary>
        internal static string TRADE_MARKET_ITEM_DEAD_ONE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ITEM_DEAD_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 침묵하는.
        /// </summary>
        internal static string TRADE_MARKET_ITEM_DEAD_THREE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ITEM_DEAD_THREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일그러진.
        /// </summary>
        internal static string TRADE_MARKET_ITEM_DEAD_TWO {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ITEM_DEAD_TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 장.
        /// </summary>
        internal static string TRADE_MARKET_ITEM_ENCHANT_GRADE_1 {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ITEM_ENCHANT_GRADE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 광.
        /// </summary>
        internal static string TRADE_MARKET_ITEM_ENCHANT_GRADE_2 {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ITEM_ENCHANT_GRADE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 고.
        /// </summary>
        internal static string TRADE_MARKET_ITEM_ENCHANT_GRADE_3 {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ITEM_ENCHANT_GRADE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유.
        /// </summary>
        internal static string TRADE_MARKET_ITEM_ENCHANT_GRADE_4 {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ITEM_ENCHANT_GRADE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 동.
        /// </summary>
        internal static string TRADE_MARKET_ITEM_ENCHANT_GRADE_5 {
            get {
                return ResourceManager.GetString("TRADE_MARKET_ITEM_ENCHANT_GRADE_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 중국어.
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_CH_CH {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_CH-CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 독일어.
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_DE_DE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_DE-DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_EN_US {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_EN-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스페인어(남미).
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_ES_ES {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_ES-ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스페인어(북미).
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_ES_SP {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_ES-SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프랑스어.
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_FR_FR {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_FR-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인도어.
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_ID_ID {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_ID-ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일본어.
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_JA_JP {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_JA-JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한국어.
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_KO_KR {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_KO-KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 포르투갈어.
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_PT_PT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_PT-PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 러시아어.
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_RU_RU {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_RU-RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 태국어.
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_TH_TH {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_TH-TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_TR_TR {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_TR-TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 중국어(대만).
        /// </summary>
        internal static string TRADE_MARKET_LANGUAGE_ZH_TW {
            get {
                return ResourceManager.GetString("TRADE_MARKET_LANGUAGE_ZH-TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 수량.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_AMOUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_BUY {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 누적 거래량.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_CUMULATIVE_VOLUME {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_CUMULATIVE_VOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소지 금액.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_CURRENT_SILVER {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_CURRENT_SILVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 예약구매.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_MENU_BIDDING_BUY {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_MENU_BIDDING_BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 예약판매.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_MENU_BIDDING_SELL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_MENU_BIDDING_SELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 거래 시장.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_MENU_MARKET {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_MENU_MARKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 내 물품.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_MENU_WALLET {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_MENU_WALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 내 계좌.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_MY_ACCOUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_MY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 개수.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_REGIST_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_REGIST_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_SEARCH {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 물품명을 입력해주세요..
        /// </summary>
        internal static string TRADE_MARKET_MAIN_SEARCH_NEED_TEXT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_SEARCH_NEED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로고침.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_SEARCH_REFRESH {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_SEARCH_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 무게.
        /// </summary>
        internal static string TRADE_MARKET_MAIN_WEIGHT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAIN_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서비스 안정화를 위한 점검이 진행 중입니다&lt;br /&gt;점검이 종료된 후 이용을 부탁드리며, 점검 시간 등 자세한 사항은 홈페이지 공지사항을 참고해주시기 바랍니다..
        /// </summary>
        internal static string TRADE_MARKET_MAINTENANCE_CONTENTS_1 {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAINTENANCE_CONTENTS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 서버 안정화를 위한 점검이 진행중입니다..
        /// </summary>
        internal static string TRADE_MARKET_MAINTENANCE_CONTENTS_2 {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAINTENANCE_CONTENTS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 점검 안내.
        /// </summary>
        internal static string TRADE_MARKET_MAINTENANCE_TITLE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MAINTENANCE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매.
        /// </summary>
        internal static string TRADE_MARKET_MY_WALLET_SELL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_MY_WALLET_SELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모바일 통합거래소를 사용하기 위해서는 가문명이 생성되어 있는 계정이어야 합니다..
        /// </summary>
        internal static string TRADE_MARKET_NOT_EXISTS_MY_WALLET_TEXT1 {
            get {
                return ResourceManager.GetString("TRADE_MARKET_NOT_EXISTS_MY_WALLET_TEXT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 게임 내에서 거래소 가방을 1회 이용하셔야 웹/모바일 통합거래소를 정상적으로 이용하실 수 있습니다..
        /// </summary>
        internal static string TRADE_MARKET_NOT_EXISTS_MY_WALLET_TEXT2 {
            get {
                return ResourceManager.GetString("TRADE_MARKET_NOT_EXISTS_MY_WALLET_TEXT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 모바일 통합거래소를 사용하시려면&lt;br /&gt;아래 내용을 참고해 주세요..
        /// </summary>
        internal static string TRADE_MARKET_NOT_EXISTS_MY_WALLET_TITLE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_NOT_EXISTS_MY_WALLET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP 인증.
        /// </summary>
        internal static string TRADE_MARKET_OTP_TITLE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_OTP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인증 앱의 OTP 인증코드를 입력해 주세요..
        /// </summary>
        internal static string TRADE_MARKET_OTP_TITLE_DESC {
            get {
                return ResourceManager.GetString("TRADE_MARKET_OTP_TITLE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이 사이트는 모바일 브라우저에 최적화 되어 있습니다.&lt;br /&gt;통합거래소를 이용하시려면 모바일 브라우저를 이용해 주세요..
        /// </summary>
        internal static string TRADE_MARKET_PC_BROWSER_ERROR {
            get {
                return ResourceManager.GetString("TRADE_MARKET_PC_BROWSER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 해당 브라우저에서는 통합 거래소 이용이 불가합니다.&lt;br /&gt;모바일 기기 혹은 PC 크롬 브라우저를 이용해주세요..
        /// </summary>
        internal static string TRADE_MARKET_PC_BROWSER_NOT_ALLOW {
            get {
                return ResourceManager.GetString("TRADE_MARKET_PC_BROWSER_NOT_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 재등록하려면 거래용 창고에 상품을 보관해 주세요..
        /// </summary>
        internal static string TRADE_MARKET_RETRY_CHECK {
            get {
                return ResourceManager.GetString("TRADE_MARKET_RETRY_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 재등록.
        /// </summary>
        internal static string TRADE_MARKET_RETRY_SELLBUY {
            get {
                return ResourceManager.GetString("TRADE_MARKET_RETRY_SELLBUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 거상.
        /// </summary>
        internal static string TRADE_MARKET_RINGBUFF {
            get {
                return ResourceManager.GetString("TRADE_MARKET_RINGBUFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 거래 우대.
        /// </summary>
        internal static string TRADE_MARKET_RINGBUFF_PREF {
            get {
                return ResourceManager.GetString("TRADE_MARKET_RINGBUFF_PREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 검색 결과.
        /// </summary>
        internal static string TRADE_MARKET_SEARCH_RESULT_TEXT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SEARCH_RESULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소.
        /// </summary>
        internal static string TRADE_MARKET_SECONDPWD_CANCEL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SECONDPWD_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인.
        /// </summary>
        internal static string TRADE_MARKET_SECONDPWD_CONFIRM {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SECONDPWD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2차 비밀번호가 틀렸습니다..
        /// </summary>
        internal static string TRADE_MARKET_SECONDPWD_FAIL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SECONDPWD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 게임에서 사용중인 2차 비밀번호를 입력해 주세요..
        /// </summary>
        internal static string TRADE_MARKET_SECONDPWD_INSERT1 {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SECONDPWD_INSERT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6자리 이상 숫자를 빈칸 없이 입력해 주세요..
        /// </summary>
        internal static string TRADE_MARKET_SECONDPWD_INSERT2 {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SECONDPWD_INSERT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 본인 확인.
        /// </summary>
        internal static string TRADE_MARKET_SECONDPWD_MYINFO {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SECONDPWD_MYINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2차 비밀번호 입력횟수를 초과하였습니다.\n24시간 동안 접속이 불가능 합니다..
        /// </summary>
        internal static string TRADE_MARKET_SECONDPWD_RETRY {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SECONDPWD_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소를 이용하실 &lt;br/&gt; 지역을 선택해 주세요..
        /// </summary>
        internal static string TRADE_MARKET_SELECT_SERVER_DESC {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELECT_SERVER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 유럽.
        /// </summary>
        internal static string TRADE_MARKET_SELECT_SERVER_EU {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELECT_SERVER_EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글로벌.
        /// </summary>
        internal static string TRADE_MARKET_SELECT_SERVER_GLOBAL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELECT_SERVER_GLOBAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아시아.
        /// </summary>
        internal static string TRADE_MARKET_SELECT_SERVER_KOREA {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELECT_SERVER_KOREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 북미.
        /// </summary>
        internal static string TRADE_MARKET_SELECT_SERVER_NA {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELECT_SERVER_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 지역 선택.
        /// </summary>
        internal static string TRADE_MARKET_SELECT_SERVER_TITLE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELECT_SERVER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 예약 완료하였습니다..
        /// </summary>
        internal static string TRADE_MARKET_SELL_BIDDING_SUCCESS {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_BIDDING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 밸류 패키지 버프 적용 시 수령액의 30%를 추가로 받을 수 있습니다. 지금 정산을 하시겠습니까?.
        /// </summary>
        internal static string TRADE_MARKET_SELL_CALCULATE_VALUE_PACKAGE_CONFIRM {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_CALCULATE_VALUE_PACKAGE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 등록.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기준가.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_BASE_PRICE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_BASE_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정산.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_CALCULATE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 취소.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_CANCEL {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매등록을 취소하시겠습니까?.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_CANCEL_CONFIRM {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_CANCEL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_CLOSE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 물품 등록.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_OK {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 개당 가격.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_PRICE_PER_ONE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_PRICE_PER_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 변경.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_PRICE_PER_ONE_CHANGE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_PRICE_PER_ONE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 물품개수.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_QUANTITY {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 개수.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_RESERVE_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_RESERVE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 수량.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_SELL_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_SELL_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 완료.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_SOLD_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_SOLD_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 회수.
        /// </summary>
        internal static string TRADE_MARKET_SELL_REGIST_WITHDRAW {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_REGIST_WITHDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 등록 완료하였습니다..
        /// </summary>
        internal static string TRADE_MARKET_SELL_SUCCESS {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 총 판매 금액.
        /// </summary>
        internal static string TRADE_MARKET_SELL_TOTAL_PRICE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_TOTAL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 밸류 패키지 버프 적용 시 수령액의 30%를 추가로 받을 수 있습니다. 지금 판매를 하시겠습니까?.
        /// </summary>
        internal static string TRADE_MARKET_SELL_VALUE_PACKAGE_CONFIRM {
            get {
                return ResourceManager.GetString("TRADE_MARKET_SELL_VALUE_PACKAGE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 총 매물.
        /// </summary>
        internal static string TRADE_MARKET_TOTAL_SALE_COUNT {
            get {
                return ResourceManager.GetString("TRADE_MARKET_TOTAL_SALE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 대기 상품.
        /// </summary>
        internal static string TRADE_MARKET_WAIT_LIST {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WAIT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 처리 중 문제가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_BuyBiddingFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_BuyBiddingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구매 처리를 시도하다가 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_BuyBiddingRepeatOverFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_BuyBiddingRepeatOverFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소 내부 처리 중 문제가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_DBException {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_DBException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소 처리 중 네트워크 문제가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_HttpException {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_HttpException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소의 아이템 수량이 잘못되었습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_InvalidCount {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_InvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소에 등록할 수 없는 아이템입니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_InvalidItem {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소에 등록할 수 없는 인챈트레벨이 포함되어 있습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_InvalidItemGroup {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_InvalidItemGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 등록 또는 회수 시 한번에 처리할 수 있는 수량을 벗어났습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_InvalidItemStack {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_InvalidItemStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최대 거래량을 넘어서 판매 또는 구매할 수 없습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_ItemCountOver {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_ItemCountOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소에 아이템이 없습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_ItemNotExist {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_ItemNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소 처리 중 문제가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_JSONException {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_JSONException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소 처리 결과가 잘못되었습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_JSONIsNull {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_JSONIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소의 결과가 잘못되었습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_PayloadIsZero {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_PayloadIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가격이 비정상입니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_PriceWrong {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_PriceWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기준가 보다 높게 가격을 설정해야 구매 예약을 할 수 있습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_ReserveBuyBiddingFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_ReserveBuyBiddingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기준가 보다 낮게 가격을 설정해야 판매 예약을 할 수 있습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_ReserveSellBiddingFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_ReserveSellBiddingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 처리 중 문제가 발생했습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_SellBiddingFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_SellBiddingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 판매 처리가 실패했습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_SellBiddingRepeatOverFail {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_SellBiddingRepeatOverFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한번에 검색될 수 있는 아이템 수가 많습니다. .
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_StringOver {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_StringOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통합거래소에 유저 정보가 존재하지 않습니다..
        /// </summary>
        internal static string TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_UserNotExist {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WEB_ERROR_eWorldTradeMarketErrorNo_UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다시 돌아오신 것을 환영합니다! &lt;br/&gt;&lt;br/&gt;모험가님의 비접속 시간에 따른 복귀 특별 지원 혜택이 시작되었습니다. &lt;br/&gt;상세 혜택이 궁금하시다면, 이벤트 게시판에서 신규/복귀 모험가를 위한 공지를 확인해주세요! &lt;br/&gt;&lt;br/&gt;검은사막에서의 멋진 플레이와 득템을 기원하며 &lt;br/&gt;우린 하나란 걸 잊지 마세요! &lt;br/&gt;&lt;br/&gt; -검은사막-.
        /// </summary>
        internal static string TRADE_MARKET_WELCOME_RETURNERS_DESC {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WELCOME_RETURNERS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오랜만이에요 복귀 모험가님!.
        /// </summary>
        internal static string TRADE_MARKET_WELCOME_RETURNERS_TITLE {
            get {
                return ResourceManager.GetString("TRADE_MARKET_WELCOME_RETURNERS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright ⓒ PearlAbyss Corp. All rights reserved..
        /// </summary>
        internal static string WEB_CONTENTS_COPYRIGHT_COMMON {
            get {
                return ResourceManager.GetString("WEB_CONTENTS_COPYRIGHT_COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackDesert - 웹 통합 거래소.
        /// </summary>
        internal static string WEB_CONTENTS_TITLE {
            get {
                return ResourceManager.GetString("WEB_CONTENTS_TITLE", resourceCulture);
            }
        }
    }
}
